### ISSUE TITLE
QAT device plugin built by default without kernel mode

### ISSUE THREAD

**Issue by ipuustin** [intel/kubernetes-qat-envoy#35]
Following the instructions in the README, after building the QAT device plugin image and deploying it as DaemonSet, the DP pod fails to launch with error message:

    kernel mode is not supported in this build. Use 'kerneldrv' build tag to have this mode enabled. Exiting...

**Comment by mythi** [comment]
@ipuustin is this with the version that comes with git submodules?

**Comment by ipuustin** [comment]
@mythi You're right, it seems that I might have had a too recent version of `intel-device-plugins-for-kubernetes`. This issue is probably not valid, so closing.

Curiously, it seems that even when compiling with `make BUILDTAGS=kerneldrv intel-qat-plugin` doesn't seem to propagate the `kerneldrv` tag to Docker build process:

    Step 9/18 : ARG TAGS_KERNELDRV=
     ---> Running in 6ac3ccad1fbd
