### ISSUE TITLE
Downloading file larger than 65536 bytes fails with qatzip enabled envoy in a Kata Container

### ISSUE THREAD

**Issue by ericwadams** [intel/kubernetes-qat-envoy#49]
I built a QATzip enabled Envoy with the `Dockerfile.openssl` in the `qatzip` branch and launched it with Kata containers.  If I try to curl download and decompress a text file with HTTP compression  enabled that is larger than 65,536 bytes,, it fails with `curl: (23) Failed reading the chunked-encoded stream`.  If I try to display the text file in a browser, then only the first 65,536 bytes are displayed.  If I do the same tasks but using software gzip compression for envoy it works without issue.

**Steps to Reproduce**

0. Enable hugepages on the server with 15000 2MB hugepages
1. Start Kubernetes cluster with either CRIO or containerd
2. Enable QAT vf's
3. Build Kata kernel and rootfs with QAT driver enabled
4. Install Kata into your kubernetes cluster with Kata-deploy
5. Start QAT plugin
6. Update Kata configuration.toml to enable hugepages and to use custom QAT kata kernel and rootfs
7. Apply both yaml files attached to start the deployments to use QAT.
8. Try to display text file in a browser and observe it doesn't fully display.
9. Alternatively, try to curl download the file and decompress at the same time. It fails with the error above.

The `nginxsupersmall1.txt` file works but `nginsxlarge1.txt` file does not.

You can use `dd if=/dev/urandom bs=1M count=100|xxd -ps -c 64 > nginxlarge1.txt` to generate some files

```
#QATzip. Second curl fails
curl -k -H 'Accept-Encoding: gzip' --compressed -O  <server>:30300/files/nginxsupersmall1.txt
curl -k -H 'Accept-Encoding: gzip' --compressed -O  <server>:30300/files/nginxlarge1.txt
#gzip  Both work
curl -k -H 'Accept-Encoding: gzip' --compressed -O  <server>:30302/files/nginxsupersmall1.txt
curl -k -H 'Accept-Encoding: gzip' --compressed -O  <server>:30302/files/nginxlarge1.txt
```

I attached the yamls for convenience. Some of the hostPath links need to be updated. Also, the `configuration-qemu.toml` needs the kernel and image path to point to the QAT kata kernel and rootfs. 

Here is a script to enable vf's

**Enable VFs**
```
sudo modprobe vfio-pci
QAT_PCI_BUS_PF_NUMBERS=$((lspci -d :435 && lspci -d :37c8 && lspci -d :19e2 && lspci -d :6f54) | cut -d ' ' -f 1)
QAT_PCI_BUS_PF_1=$(echo $QAT_PCI_BUS_PF_NUMBERS | cut -d ' ' -f 1)
echo 16 | sudo tee /sys/bus/pci/devices/0000:$QAT_PCI_BUS_PF_1/sriov_numvfs
QAT_PCI_ID_VF=$(cat /sys/bus/pci/devices/0000:${QAT_PCI_BUS_PF_1}/virtfn0/uevent | grep PCI_ID)
QAT_VENDOR_AND_ID_VF=$(echo ${QAT_PCI_ID_VF/PCI_ID=} | sed 's/:/ /')
echo $QAT_VENDOR_AND_ID_VF | sudo tee --append /sys/bus/pci/drivers/vfio-pci/new_id

for f in /sys/bus/pci/devices/0000:$QAT_PCI_BUS_PF_1/virtfn*
  do QAT_PCI_BUS_VF=$(basename $(readlink $f))
   echo $QAT_PCI_BUS_VF | sudo tee --append /sys/bus/pci/drivers/c6xxvf/unbind
   echo $QAT_PCI_BUS_VF | sudo tee --append /sys/bus/pci/drivers/vfio-pci/bind
  done
```

**Create kubernetes secret for QAT after starting control plane**
```
openssl req -x509 -new -batch -nodes -subj '/CN=localhost' -keyout key.pem -out cert.pem
kubectl create secret tls envoy-tls-secret --cert cert.pem --key key.pem
```

**Add Kata into your cluster with kata-deploy**
```
kubectl apply -f https://raw.githubusercontent.com/kata-containers/packaging/master/kata-deploy/kata-rbac/base/kata-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/kata-containers/packaging/master/kata-deploy/kata-deploy/base/kata-deploy.yaml
kubectl apply -f https://raw.githubusercontent.com/kata-containers/packaging/master/kata-deploy/k8s-1.14/kata-qemu-runtimeClass.yaml
```

Copy the `configuration-qemu.yaml` to `/opt/kata/share/defaults/kata-containers/` and edit the kernel and image paths to point to the customer kata kernel and image.

The kata kernel and rootfs is too big for me to attach to this issue. I can give separately. 

[kata-nginx-envoy-qatzip-admin.yaml.txt](https://github.com/intel/kubernetes-qat-envoy/files/4827145/kata-nginx-envoy-qatzip-admin.yaml.txt)
[kata-nginx-envoy-gzip-speed-admin.yaml.txt](https://github.com/intel/kubernetes-qat-envoy/files/4827146/kata-nginx-envoy-gzip-speed-admin.yaml.txt)
[configuration-qemu.toml.txt](https://github.com/intel/kubernetes-qat-envoy/files/4827147/configuration-qemu.toml.txt)

**Comment by mythi** [comment]
Fixed by #50
